use_frameworks!

target 'CocoapodsExample' do
    # pod 'BytegainAnalytics', :path => '../../' do
    pod 'BytegainAnalytics', '~> 4.0.2' do
    config[:bg_debug].settings['GCC_PREPROCESSOR_DEFINITIONS'] += "BG_DEBUG=1"
  end
end
